/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  Pablo Barragan
 * Created: 22-abr-2019
 */
-- DROP TABLE USUARIO;
CREATE TABLE USUARIO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDOS VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    TELEFONO VARCHAR(15),
    DIRECCION VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE,
    FOTO VARCHAR(30),
    CONSTRAINT ID_USUARIO_PK PRIMARY KEY (ID)
);
DROP TABLE PRODUCTO;
CREATE TABLE PRODUCTO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(20) NOT NULL,
    FABRICANTE VARCHAR(20) NOT NULL,
    DESCRIPCION VARCHAR(155) NOT NULL,
    NUEVO BOOLEAN NOT NULL,
    PRECIO DECIMAL(7,2) NOT NULL,
    ENVIO DECIMAL(7,2) NOT NULL,
    FOTO VARCHAR(30) NOT NULL,
    FECHA DATE DEFAULT CURRENT_DATE,
    USUARIO INTEGER NOT NULL,
    CONSTRAINT ID_PRODUCTO_PK PRIMARY KEY (ID),
    CONSTRAINT USUARIO_PRODUCTO_FK FOREIGN KEY (USUARIO) REFERENCES USUARIO (ID)
);